# Generated by Django 5.1.1 on 2024-09-26 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField(default=datetime.date(1900, 1, 1))),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('salary', models.FloatField(null=True)),
                ('memo', models.TextField()),
                ('web_site', models.URLField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'person',
                'ordering': ['salary'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='person_first_n_09097a_idx')],
            },
        ),
    ]
